export const ScenarioImages: Record<string, any> = {
  F1: require('../../../assets/images/F1.png'),
  F2: require('../../../assets/images/F2.png'),
  F3: require('../../../assets/images/F3.png'),
  F4: require('../../../assets/images/F4.png'),
  F5: require('../../../assets/images/F5.png'),
  F6: require('../../../assets/images/F6.png'),
  F7: require('../../../assets/images/F7.png'),
  F8: require('../../../assets/images/F8.png'),
  F9: require('../../../assets/images/F9.png'),
  F10: require('../../../assets/images/F10.png'),
  F11: require('../../../assets/images/F11.png'),
  F12: require('../../../assets/images/F12.png'),
  F13: require('../../../assets/images/F13.png'),
  F14: require('../../../assets/images/F14.png'),
  F15: require('../../../assets/images/F15.png'),
  F16: require('../../../assets/images/F16.png'),
  F17: require('../../../assets/images/F17.png'),
  F18: require('../../../assets/images/F18.png'),
  F19: require('../../../assets/images/F19.png'),
  F20: require('../../../assets/images/F20.png'),
  // F21: require('../../../assets/images/F21.png'),
  // F22: require('../../../assets/images/F22.png'),
  // F23: require('../../../assets/images/F23.png'),
  // F24: require('../../../assets/images/F24.png'),
  // F25: require('../../../assets/images/F25.png'),
  // F26: require('../../../assets/images/F26.png'),
  // F27: require('../../../assets/images/F27.png'),
  // F28: require('../../../assets/images/F28.png'),
  // F29: require('../../../assets/images/F29.png'),
  // F30: require('../../../assets/images/F30.png'),
  // F31: require('../../../assets/images/F31.png'),
  // F32: require('../../../assets/images/F32.png'),
  // F33: require('../../../assets/images/F33.png'),
  // F34: require('../../../assets/images/F34.png'),
  // F35: require('../../../assets/images/F35.png'),
  // F36: require('../../../assets/images/F36.png'),
  // F37: require('../../../assets/images/F37.png'),
  // F38: require('../../../assets/images/F38.png'),
  // F39: require('../../../assets/images/F39.png'),
  // F40: require('../../../assets/images/F40.png'),
  // F41: require('../../../assets/images/F41.png'),
  // F42: require('../../../assets/images/F42.png'),
  // F43: require('../../../assets/images/F43.png'),
  // F44: require('../../../assets/images/F44.png'),
  // F45: require('../../../assets/images/F45.png'),
  // F46: require('../../../assets/images/F46.png'),
  // F47: require('../../../assets/images/F47.png'),
  // F48: require('../../../assets/images/F48.png'),
  // F49: require('../../../assets/images/F49.png'),
  // F50: require('../../../assets/images/F50.png'),

  S1: require('../../../assets/images/S1.jpg'),
  S2: require('../../../assets/images/S2.jpg'),
  S3: require('../../../assets/images/S3.jpg'),
  S4: require('../../../assets/images/S4.jpg'),
  S5: require('../../../assets/images/S5.jpg'),
  S6: require('../../../assets/images/S6.jpg'),
  S7: require('../../../assets/images/S7.jpg'),
  S8: require('../../../assets/images/S8.jpg'),
  S9: require('../../../assets/images/S9.jpg'),
  S10: require('../../../assets/images/S10.jpg'),
  S11: require('../../../assets/images/S11.jpg'),
  S12: require('../../../assets/images/S12.jpg'),
  S13: require('../../../assets/images/S13.jpg'),
  S14: require('../../../assets/images/S14.jpg'),
  S15: require('../../../assets/images/S15.jpg'),
  S16: require('../../../assets/images/S16.jpg'),
  S17: require('../../../assets/images/S17.jpg'),
  S18: require('../../../assets/images/S18.jpg'),
  S19: require('../../../assets/images/S19.jpg'),
  S20: require('../../../assets/images/S20.jpg'),
  // S21: require('../../../assets/images/S21.jpg'),
  // S22: require('../../../assets/images/S22.jpg'),
  // S23: require('../../../assets/images/S23.jpg'),
  // S24: require('../../../assets/images/S24.jpg'),
  // S25: require('../../../assets/images/S25.jpg'),
  // S26: require('../../../assets/images/S26.jpg'),
  // S27: require('../../../assets/images/S27.jpg'),
  // S28: require('../../../assets/images/S28.jpg'),
  // S29: require('../../../assets/images/S29.jpg'),
  // S30: require('../../../assets/images/S30.jpg'),
  // S31: require('../../../assets/images/S31.jpg'),
  // S32: require('../../../assets/images/S32.jpg'),
  // S33: require('../../../assets/images/S33.jpg'),
  // S34: require('../../../assets/images/S34.jpg'),
  // S35: require('../../../assets/images/S35.jpg'),
  // S36: require('../../../assets/images/S36.jpg'),
  // S37: require('../../../assets/images/S37.jpg'),
  // S38: require('../../../assets/images/S38.jpg'),
  // S39: require('../../../assets/images/S39.jpg'),
  // S40: require('../../../assets/images/S40.jpg'),
  // S41: require('../../../assets/images/S41.jpg'),
  // S42: require('../../../assets/images/S42.jpg'),
  // S43: require('../../../assets/images/S43.jpg'),
  // S44: require('../../../assets/images/S44.jpg'),
  // S45: require('../../../assets/images/S45.jpg'),
  // S46: require('../../../assets/images/S46.jpg'),
  // S47: require('../../../assets/images/S47.jpg'),
  // S48: require('../../../assets/images/S48.jpg'),
  // S49: require('../../../assets/images/S49.jpg'),
  // S50: require('../../../assets/images/S50.jpg'),

  T1: require('../../../assets/images/T1.jpg'),
  T2: require('../../../assets/images/T2.jpg'),
  T3: require('../../../assets/images/T3.jpg'),
  T4: require('../../../assets/images/T4.jpg'),
  T5: require('../../../assets/images/T5.jpg'),
  T6: require('../../../assets/images/T6.jpg'),
  T7: require('../../../assets/images/T7.jpg'),
  T8: require('../../../assets/images/T8.jpg'),
  T9: require('../../../assets/images/T9.jpg'),
  T10: require('../../../assets/images/T10.jpg'),
  T11: require('../../../assets/images/T11.jpg'),
  T12: require('../../../assets/images/T12.jpg'),
  T13: require('../../../assets/images/T13.jpg'),
  T14: require('../../../assets/images/T14.jpg'),
  T15: require('../../../assets/images/T15.jpg'),
  T16: require('../../../assets/images/T16.jpg'),
  T17: require('../../../assets/images/T17.jpg'),
  T18: require('../../../assets/images/T18.jpg'),
  T19: require('../../../assets/images/T19.jpg'),
  T20: require('../../../assets/images/T20.jpg'),
  // T21: require('../../../assets/images/T21.jpg'),
  // T22: require('../../../assets/images/T22.jpg'),
  // T23: require('../../../assets/images/T23.jpg'),
  // T24: require('../../../assets/images/T24.jpg'),
  // T25: require('../../../assets/images/T25.jpg'),
  // T26: require('../../../assets/images/T26.jpg'),
  // T27: require('../../../assets/images/T27.jpg'),
  // T28: require('../../../assets/images/T28.jpg'),
  // T29: require('../../../assets/images/T29.jpg'),
  // T30: require('../../../assets/images/T30.jpg'),
  // T31: require('../../../assets/images/T31.jpg'),
  // T32: require('../../../assets/images/T32.jpg'),
  // T33: require('../../../assets/images/T33.jpg'),
  // T34: require('../../../assets/images/T34.jpg'),
  // T35: require('../../../assets/images/T35.jpg'),
  // T36: require('../../../assets/images/T36.jpg'),
  // T37: require('../../../assets/images/T37.jpg'),
  // T38: require('../../../assets/images/T38.jpg'),
  // T39: require('../../../assets/images/T39.jpg'),
  // T40: require('../../../assets/images/T40.jpg'),
  // T41: require('../../../assets/images/T41.jpg'),
  // T42: require('../../../assets/images/T42.jpg'),
  // T43: require('../../../assets/images/T43.jpg'),
  // T44: require('../../../assets/images/T44.jpg'),
  // T45: require('../../../assets/images/T45.jpg'),
  // T46: require('../../../assets/images/T46.jpg'),
  // T47: require('../../../assets/images/T47.jpg'),
  // T48: require('../../../assets/images/T48.jpg'),
  // T49: require('../../../assets/images/T49.jpg'),
  // T50: require('../../../assets/images/T50.jpg'),
};
